[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"

[features]
user-test = []
sched-demo = []
ext4-write-test = []
net-loopback-test = []
user-tcp-echo = []

[dependencies]
axfs = { path = "../axfs" }
axnet = { path = "../axnet" }
