[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"

[features]
user-test = []
user-shell = []
sched-demo = []
ext4-write-test = []
net-loopback-test = []
user-tcp-echo = []
user-udp-echo = []
user-fs-smoke = []

[dependencies]
axfs = { path = "../axfs" }
axnet = { path = "../axnet" }
