[workspace]
resolver = "2"
members = [
  "modules/axfs",
  "modules/axnet",
  "modules/axruntime",
  "crates/axvfs",
]

[workspace.package]
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
